### ISSUE TITLE
add debug help section

### ISSUE THREAD

**Issue by Mudartastisch** [Nekolike/Mappy#13]
The main script requires to be run as admin, not everyone will be able to understand a notification like this: 
![AutoHotkey_2020-01-20_13-46-07](https://user-images.githubusercontent.com/8214824/72727459-43ab1580-3b8b-11ea-8a36-96d00e0d775b.png)

Add a debug section containing a simple step by step guide like:

- go to your AutoHotkey install folder
- AutoHotkey -> right-click -> Properties
- Compatibility -> Run this program as an administrator
- Apply, OK

**Comment by Nekolike** [comment]
I have added a try-catch block which will result in the same behaviour as using your step-by-step guide. Thank you for the report!
