### ISSUE TITLE
"ERROR" is not a valid keyname

### ISSUE THREAD

**Issue by RyShabz** [Nekolike/Mappy#3]
Error occurs on Mappy.ahk launch. Win10. 
Error refers to line 87: Hotkey, %ToggleOverlayHotkey%, ToggleOverlay, On
![image](https://user-images.githubusercontent.com/53990165/72671865-26990a00-3a06-11ea-8cae-56fa3c0e6c8f.png)

**Comment by Nekolike** [comment]
Do you know what you've done/tried to do before the error occured? The error seems to be related to the Settings.ini which should contain a line saying "ToggleKey=...". Could you check wether that's the case?

**Comment by RyShabz** [comment]
I've done nothing. I unzipped and clicked the .ahk and got that error. It was literally my first interaction with the tool. _Region works, however.

**Comment by Nekolike** [comment]
Okay, maybe the files couldn't get created. Could you check the folder containing the Mappy.ahk and see if there's a "Config.ini" and a "Settings.ini". If they are there, can you open the "Settings.ini" with any editor and either screenshot or tell me what's written in there?

**Comment by Nekolike** [comment]
I have updated Mappy to ask for admin rights first, it might have been related to that. If that fixes the issue (you should get an update message when you reload the script or start Mappy again to get the new version) please confirm that or keep on reporting if it didn't. Thank you for your help!

**Comment by RyShabz** [comment]
That fixed it. Needed admin rights.
